Just curious

diff --git a/.github/workflows/ci-generate.yaml b/.github/workflows/ci-generate.yaml
--- a/.github/workflows/ci-generate.yaml
+++ b/.github/workflows/ci-generate.yaml
@@ -49,7 +49,8 @@ jobs:
             generated_file="${check_file%.check}"
             if ! diff "${check_file}" "${generated_file}" > /dev/null ; then
               echo "File ${generated_file} has changed from ${generated_file}.template:"
-              diff "${check_file}" "${generated_file}"
+              diff "${check_file}" "${generated_file}" || true
+              echo "::error file=${generated_file}::Template change detected."
               change_detected=true
             fi
           done
